apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
        version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: spring
          image: jaksonsneider/spring:v2
          ports:
            - containerPort: 8081
          resources:
          env:
            - name: VERSION
              value: "1.0.0"
