apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-color
  template:
    metadata:
      labels:
        app: nginx-color
    spec:
      containers:
        - name: nginx-color
          image: kubedevio/nginx-color:blue

          # ports:
          #   - containerPort: 3000

          # env:
          #   - name: USERNAME
          #     value: nginx
          #   - name: PASSWORD
          #     value: nginx12345

          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: "1"
          #   requests:
          #     memory: 256Mi
          #     cpu: "0.2"
