apiVersion: v1
kind: Pod
metadata:
  name: meupod
  labels:
    app: nginx-color
spec:
  containers:
    - name: nginx-color
      image: kubedevio/nginx-color:blue

      # resources:
      #   limits:
      #     memory: 512Mi
      #     cpu: "1"
      #   requests:
      #     memory: 256Mi
      #     cpu: "0.2"
