apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: jaksonsneider@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: NzVlYmE1MzBiM2U2YjMyYWE0MTk2MjlmYTFiY2E5YmQwZDdlYTZkZDhmN2Y5MmIzMzI3YmVmOTcwMjFhZmU1ZA==
      selector:
        dnsNames:
        - 'jwsystem.com.br'
        - '*.jwsystem.com.br'