apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
data:
  # insert your DO access token here
  access-token: "NzVlYmE1MzBiM2U2YjMyYWE0MTk2MjlmYTFiY2E5YmQwZDdlYTZkZDhmN2Y5MmIzMzI3YmVmOTcwMjFhZmU1ZA=="