apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: busybox
  template:
    metadata:
      labels:
        tier: busybox
  spec:
    containers:
      - name: busybox
        image: radial/busyboxplus:curl
