apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-v2
  labels:
    nginx: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: replica-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: jaksonsneider/nginx:red
          ports:
            - containerPort: 80
          resources:
