apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  ports:
    - nodePort: 30000
      port: 8080
      targetPort: 80
      name: "port-1"
    - nodePort: 30002
      port: 80
      targetPort: 80
      name: "port-2"
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
