apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: appdaemonset
  namespace: default
  labels:
    app: daemonset
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: jaksonsneider/nginx:blue
          ports:
            - containerPort: 80
  updateStrategy:
    type: RollingUpdate
