apiVersion: v1
kind: LimitRange
metadata:
  name: limitando-recursos
spec:
  limits:
    - default:
        cpu: "2"
        memory: "4Gi"
      defaultRequest:
        cpu: "1"
        memory: "2Gi"
      type: Container
