apiVersion: v1
kind: Service
metadata:
  name: app-deployment
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31077
  selector:
    app: nginx
  type: LoadBalancer
  sessionAffinity: None
