apiVersion: v1
kind: Service
metadata:
  name: app-deployment
  namespace: default
spec:
  ports:
    - nodePort: 31077
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
