apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-job
              image: busybox
              args:
                - /bin/sh
                - -c
                - data; echo Bem vindo ao Descomplicando Kubernetes - LinuxTips VAAIIII ;sleep 30
          restartPolicy: OnFailure
