# sudo apt-get install nfs-kernel-server

# sudo nano /etc/exports

# /opt/dados *(rw,sync,no_root_squash,subtree_check)

#  sudo exportfs -ar

# sudo apt-get install nfs-common

# showmount -e 172.31.36.93

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Mi
