apiVersion: v1
kind: Pod
metadata:
  name: busy-configmap
  namespace: default
  labels:
    app: busy-configmap
spec:
  containers:
    - name: busy-configmap
      image: busybox
      resources:
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: meu-configmap-vol
          mountPath: /etc/lima
  volumes:
    - name: meu-configmap-vol
      configMap:
        name: cores-frutas
