apiVersion: v1
kind: Pod
metadata:
  name: test-secret
  namespace: default
spec:
  containers:
    - name: secret-pod
      image: busybox
      resources:
      command:
        - "sleep"
        - "3600"
      volumeMounts:
        - mountPath: /tmp/lima
          name: my-volume-secret
  volumes:
    - name: my-volume-secret
      secret:
        secretName: secret
