apiVersion: v1
kind: Pod
metadata:
  name: init-demo-v1
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
      ports:
        - containerPort: 80
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
  initContainers:
    - name: install
      image: busybox
      command: ["wget", "-O", "/work-dir/index.html", "http://linuxtips.io"]
      volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
    - name: workdir
      emptyDir: {}
