apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-app
spec:
  acme:
    email: jaksonsneiderx@gmail.com
    privateKeySecretRef:
      name: letsencrypt-app-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
